[package]
name = "bsgraphlib-rs"
version = "0.1.0"
authors = ["Clara Carrasquel Fiorini"]
edition = "2021"
license = "MIT"
repository = "https://github.com/ClaraCF/BsGraphLib-rs"
readme = "README.md"

[lib]
name = "bsgraphlib"

[dependencies]
